- id: '1593371636159'
  alias: Lights on in the evening
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - after: '13:00:00'
    before: '22:00:00'
    condition: time
  action:
  - data: {}
    entity_id: switch.tradfri_outlet,switch.tradfri_outlet_2
    service: switch.turn_on
  - data: {}
    entity_id: light.front_door
    service: light.turn_on
  mode: single
- id: '1595777315473'
  alias: Lights off when it is bedtime
  description: ''
  trigger:
  - at: '23:30:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.tradfri_outlet,switch.tradfri_outlet_2
    service: switch.turn_off
  - data: {}
    entity_id: light.front_door
    service: light.turn_off
  mode: single
